const initialLivros = [
  // --- 39 livros do Antigo Testamento ---
  { nome: "Gênesis", testamento: "antigo" },
  { nome: "Êxodo", testamento: "antigo" },
  { nome: "Levítico", testamento: "antigo" },
  { nome: "Números", testamento: "antigo" },
  { nome: "Deuteronômio", testamento: "antigo" },
  { nome: "Josué", testamento: "antigo" },
  { nome: "Juízes", testamento: "antigo" },
  { nome: "Rute", testamento: "antigo" },
  { nome: "I Samuel", testamento: "antigo" },
  { nome: "II Samuel", testamento: "antigo" },
  { nome: "I Reis", testamento: "antigo" },
  { nome: "II Reis", testamento: "antigo" },
  { nome: "I Crônicas", testamento: "antigo" },
  { nome: "II Crônicas", testamento: "antigo" },
  { nome: "Esdras", testamento: "antigo" },
  { nome: "Neemias", testamento: "antigo" },
  { nome: "Ester", testamento: "antigo" },
  { nome: "Jó", testamento: "antigo" },
  { nome: "Salmos", testamento: "antigo" },
  { nome: "Provérbios", testamento: "antigo" },
  { nome: "Eclesiastes", testamento: "antigo" },
  { nome: "Cânticos", testamento: "antigo" },
  { nome: "Isaías", testamento: "antigo" },
  { nome: "Jeremias", testamento: "antigo" },
  { nome: "Lamentações", testamento: "antigo" },
  { nome: "Ezequiel", testamento: "antigo" },
  { nome: "Daniel", testamento: "antigo" },
  { nome: "Oséias", testamento: "antigo" },
  { nome: "Joel", testamento: "antigo" },
  { nome: "Amós", testamento: "antigo" },
  { nome: "Obadias", testamento: "antigo" },
  { nome: "Jonas", testamento: "antigo" },
  { nome: "Miqueias", testamento: "antigo" },
  { nome: "Naum", testamento: "antigo" },
  { nome: "Habacuque", testamento: "antigo" },
  { nome: "Sofonias", testamento: "antigo" },
  { nome: "Ageu", testamento: "antigo" },
  { nome: "Zacarias", testamento: "antigo" },
  { nome: "Malaquias", testamento: "antigo" },

  // --- 27 livros do Novo Testamento ---
  { nome: "Mateus", testamento: "novo" },
  { nome: "Marcos", testamento: "novo" },
  { nome: "Lucas", testamento: "novo" },
  { nome: "João", testamento: "novo" },
  { nome: "Atos", testamento: "novo" },
  { nome: "Romanos", testamento: "novo" },
  { nome: "I Coríntios", testamento: "novo" },
  { nome: "II Coríntios", testamento: "novo" },
  { nome: "Gálatas", testamento: "novo" },
  { nome: "Efésios", testamento: "novo" },
  { nome: "Filipenses", testamento: "novo" },
  { nome: "Colossenses", testamento: "novo" },
  { nome: "I Tessalonicenses", testamento: "novo" },
  { nome: "II Tessalonicenses", testamento: "novo" },
  { nome: "I Timóteo", testamento: "novo" },
  { nome: "II Timóteo", testamento: "novo" },
  { nome: "Tito", testamento: "novo" },
  { nome: "Filemom", testamento: "novo" },
  { nome: "Hebreus", testamento: "novo" },
  { nome: "Tiago", testamento: "novo" },
  { nome: "I Pedro", testamento: "novo" },
  { nome: "II Pedro", testamento: "novo" },
  { nome: "I João", testamento: "novo" },
  { nome: "II João", testamento: "novo" },
  { nome: "III João", testamento: "novo" },
  { nome: "Judas", testamento: "novo" },
  { nome: "Apocalipse", testamento: "novo" }
];

export default initialLivros;