const initialLivros = [
  // --- 27 livros do Antigo Testamento ---
  { nome: "Gênesis", testamento: "antigo" },
  { nome: "Êxodo", testamento: "antigo" },
  { nome: "Levítico", testamento: "antigo" },
  { nome: "Números", testamento: "antigo" },
  { nome: "Deuteronômio", testamento: "antigo" },
  { nome: "Josué", testamento: "antigo" },
  { nome: "Juízes", testamento: "antigo" },
  { nome: "Rute", testamento: "antigo" },
  { nome: "1 Samuel", testamento: "antigo" },
  { nome: "2 Samuel", testamento: "antigo" },
  { nome: "1 Reis", testamento: "antigo" },
  { nome: "2 Reis", testamento: "antigo" },
  { nome: "1 Crônicas", testamento: "antigo" },
  { nome: "2 Crônicas", testamento: "antigo" },
  { nome: "Esdras", testamento: "antigo" },
  { nome: "Neemias", testamento: "antigo" },
  { nome: "Ester", testamento: "antigo" },
  { nome: "Jó", testamento: "antigo" },
  { nome: "Salmos", testamento: "antigo" },
  { nome: "Provérbios", testamento: "antigo" },
  { nome: "Eclesiastes", testamento: "antigo" },
  { nome: "Cânticos", testamento: "antigo" },
  { nome: "Isaías", testamento: "antigo" },
  { nome: "Jeremias", testamento: "antigo" },
  { nome: "Lamentações", testamento: "antigo" },
  { nome: "Ezequiel", testamento: "antigo" },
  { nome: "Daniel", testamento: "antigo" },

  // --- 27 livros do Novo Testamento ---
  { nome: "Mateus", testamento: "novo" },
  { nome: "Marcos", testamento: "novo" },
  { nome: "Lucas", testamento: "novo" },
  { nome: "João", testamento: "novo" },
  { nome: "Atos", testamento: "novo" },
  { nome: "Romanos", testamento: "novo" },
  { nome: "1 Coríntios", testamento: "novo" },
  { nome: "2 Coríntios", testamento: "novo" },
  { nome: "Gálatas", testamento: "novo" },
  { nome: "Efésios", testamento: "novo" },
  { nome: "Filipenses", testamento: "novo" },
  { nome: "Colossenses", testamento: "novo" },
  { nome: "1 Tessalonicenses", testamento: "novo" },
  { nome: "2 Tessalonicenses", testamento: "novo" },
  { nome: "1 Timóteo", testamento: "novo" },
  { nome: "2 Timóteo", testamento: "novo" },
  { nome: "Tito", testamento: "novo" },
  { nome: "Filemom", testamento: "novo" },
  { nome: "Hebreus", testamento: "novo" },
  { nome: "Tiago", testamento: "novo" },
  { nome: "1 Pedro", testamento: "novo" },
  { nome: "2 Pedro", testamento: "novo" },
  { nome: "1 João", testamento: "novo" },
  { nome: "2 João", testamento: "novo" },
  { nome: "3 João", testamento: "novo" },
  { nome: "Judas", testamento: "novo" },
  { nome: "Apocalipse", testamento: "novo" }
];

export default initialLivros;